@BaseUrl=https://c3vehicleapi.azurewebsites.net/
@ApplicationName=REPLACE_ME
@ApplicationId=REPLACE_ME
@SiteId=REPLACE_ME
@ApiKey=REPLACE_ME

### Register a new application
POST {{BaseUrl}}/registrations
content-type: application/json

{
  "applicationName": "{{ApplicationName}}"
}

### Get all sites
GET {{BaseUrl}}/sites
x-api-key: {{ApiKey}}
Accept: "application/json"

### Get all appointments for a specific site
GET {{BaseUrl}}/sites/{{SiteId}}/appointments
x-api-key: {{ApiKey}}
Accept: "application/json"